// <auto-generated />
namespace NamelessWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Notoreserve : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notoreserve));
        
        string IMigrationMetadata.Id
        {
            get { return "201712231052415_No to reserve"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
